#!/bin/bash
how to build your program you have to be know 
you don't know your skills as well as anything you always thinking something about to someone else hello nag bro which i choose i do not know how to become more and more in my field but still shameless things im doing 